export const workspaceText = {
  saved: 'Все изменения сохранены',
  dirty: 'Есть несохранённые изменения',
  saving: 'Сохраняем…',
  saveFailed: 'Не удалось сохранить',
  conflict: 'Конфликт версий',
  brandIcon: '✳',
  brand: 'поток',
  beta: 'BETA',
  workspace: 'Рабочее пространство',
  demo: 'Демо-режим',
  avatar: 'Я',
  spaces: 'ПРОСТРАНСТВА',
  blocks: 'БЛОКИ КАНВАСА',
  paletteHintStart: 'Добавьте блок и соедините его',
  paletteHintEnd: 'с другими через порты.',
  prompt: 'Текст',
  promptHint: 'Описание изображения',
  generator: 'Генератор',
  generatorHint: 'Запуск генерации',
  result: 'Результат',
  resultHint: 'Готовое изображение',
  add: '+',
  keyboardConnect: 'Соединить с клавиатуры',
  connectionAdded: 'Связь добавлена.',
  invalidConnection:
    'Недопустимая связь. Соединяйте текст → генератор → результат; вход должен быть свободен.',
  source: 'Откуда',
  chooseNode: 'Выберите ноду',
  nodeSeparator: ' · ',
  target: 'Куда',
  connect: 'Соединить',
  helpIcon: 'i',
  helpStart: 'Всё начинается с идеи.',
  helpEnd: 'Расскажите её в текстовой ноде.',
  breadcrumbSpaces: 'Пространства ',
  breadcrumbSeparator: '/',
  breadcrumbCanvas: ' Канвас',
  save: 'Сохранить',
  draftDownloadHint: ' Локальные правки доступны для скачивания.',
  downloadDraft: 'Скачать черновик',
  reloadGraph: 'Перечитать серверный граф',
  retrySave: 'Повторить сохранение',
  draftAvailable: 'Есть сохранённый локальный черновик.',
  restoreDraft: 'Восстановить черновик',
  download: 'Скачать',
  welcomeEyebrow: 'ОТ ИДЕИ К ИЗОБРАЖЕНИЮ',
  welcomeTitle: 'Дайте идее форму.',
  welcomeStart: 'Соберите цепочку из трёх блоков',
  welcomeEnd: 'или начните с готового примера.',
  addExample: 'Добавить пример цепочки',
  nodeCountSuffix: ' / 20 нод ',
  separator: '·',
  edgeCountSuffix: ' / 20 связей',
  connectionHint: 'Перетащите порт, чтобы создать связь ',
  deleteHint: ' Delete — удалить',
  attribution: 'REACT FLOW',
  emptyTitle: 'Место для вашей следующей идеи.',
  loadingTitle: 'Открываем пространства…',
  emptyHint: 'Создайте пространство в меню слева.',
  defaultTitle: 'Моё пространство',
  createFirst: 'Создать первый канвас',
} as const;

export const canvasText = {
  defaultTitle: 'Моё пространство',
  invalidTitle: 'Введите название от 1 до 80 символов.',
  missingVersion: 'Сервер не вернул версию графа.',
  generator: 'Генератор',
  result: 'Результат',
  examplePrompt: 'Тихое озеро у подножия гор на рассвете, мягкий свет и лёгкий туман',
  incompleteChain: 'Соедините непустой текст, генератор и результат.',
} as const;

export const saveLabels = {
  saved: workspaceText.saved,
  dirty: workspaceText.dirty,
  saving: workspaceText.saving,
  error: workspaceText.saveFailed,
  conflict: workspaceText.conflict,
};
